[package]
name = "alexa-my-investing-briefings"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
lambda_http = { version = "0.7", default-features = false, features = ["apigw_http"] }
lambda_runtime = "0.7"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

